import {
  pgTable,
  text,
  integer,
  boolean,
  timestamp,
  jsonb,
  date,
  index,
  pgEnum,
} from "drizzle-orm/pg-core";

// Enumerated source registries
export const sourceEnum = pgEnum("source", [
  "clinicaltrials_gov",
  "ictrp",
  "anzctr",
  "chictr",
  "ctri",
  "eu_ctr",
  "isrctn",
  "jrct",
  "other",
]);

// Normalized recruitment status across registries
export const statusEnum = pgEnum("trial_status", [
  "recruiting",
  "not_yet_recruiting",
  "enrolling_by_invitation",
  "active_not_recruiting",
  "completed",
  "suspended",
  "terminated",
  "withdrawn",
  "unknown",
]);

export const trials = pgTable(
  "trials",
  {
    // Composite-feeling primary key: source-prefixed ID guarantees uniqueness across registries.
    // For ClinicalTrials.gov: "NCT05123456". For ChiCTR: "ChiCTR2400012345". Etc.
    id: text("id").primaryKey(),
    source: sourceEnum("source").notNull(),
    sourceUrl: text("source_url").notNull(),

    // The trial's "natural" ID(s) from registries — used for cross-registry deduplication.
    // e.g. a Chinese trial might list its NCT ID here in addition to its ChiCTR ID.
    crossReferenceIds: text("cross_reference_ids").array().default([]),

    // Titles & descriptions
    briefTitle: text("brief_title"),
    officialTitle: text("official_title"),
    briefSummary: text("brief_summary"),
    detailedDescription: text("detailed_description"),
    plainLanguageSummary: text("plain_language_summary"), // generated by Claude

    // Status & phase
    status: statusEnum("status").notNull().default("unknown"),
    phase: text("phase"), // "PHASE1", "PHASE2", "PHASE1_2", "NA", etc.
    studyType: text("study_type"),

    // Conditions: raw from source + our normalized cancer types
    conditions: text("conditions").array().default([]),
    cancerTypes: text("cancer_types").array().default([]), // normalized values from our taxonomy

    // Interventions
    interventions: jsonb("interventions").$type<
      Array<{
        type: string;
        name: string;
        description?: string;
      }>
    >(),
    modalities: text("modalities").array().default([]), // normalized from our taxonomy

    // Eligibility
    eligibilityCriteria: text("eligibility_criteria"),
    minAgeYears: integer("min_age_years"),
    maxAgeYears: integer("max_age_years"),
    sex: text("sex"), // "ALL" | "MALE" | "FEMALE"
    healthyVolunteers: boolean("healthy_volunteers"),

    // Enrollment & dates
    enrollmentCount: integer("enrollment_count"),
    startDate: date("start_date"),
    primaryCompletionDate: date("primary_completion_date"),
    completionDate: date("completion_date"),

    // Sponsor
    sponsorName: text("sponsor_name"),
    sponsorClass: text("sponsor_class"), // "INDUSTRY" | "OTHER" | "NIH" | etc.
    collaborators: text("collaborators").array().default([]),

    // Locations (denormalized for fast filtering)
    countries: text("countries").array().default([]),
    locations: jsonb("locations").$type<
      Array<{
        facility?: string;
        city?: string;
        state?: string;
        country: string;
        zip?: string;
        status?: string;
        latitude?: number;
        longitude?: number;
        contacts?: Array<{
          name?: string;
          role?: string;
          phone?: string;
          email?: string;
        }>;
      }>
    >(),

    // Outcomes
    primaryOutcomes: jsonb("primary_outcomes").$type<
      Array<{ measure: string; description?: string; timeFrame?: string }>
    >(),
    secondaryOutcomes: jsonb("secondary_outcomes").$type<
      Array<{ measure: string; description?: string; timeFrame?: string }>
    >(),

    // Central contacts (often more useful than location-specific)
    centralContacts: jsonb("central_contacts").$type<
      Array<{ name?: string; role?: string; phone?: string; email?: string }>
    >(),

    // Source metadata
    sourceLastUpdated: timestamp("source_last_updated", { withTimezone: true }),

    // Our metadata
    ingestedAt: timestamp("ingested_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    lastClassifiedAt: timestamp("last_classified_at", { withTimezone: true }),
    classificationVersion: integer("classification_version").default(0), // bump to force reclassification

    // Optional raw payload for re-classification or audit (can be turned off to save space)
    rawData: jsonb("raw_data"),
  },
  (table) => ({
    statusIdx: index("trials_status_idx").on(table.status),
    cancerTypesIdx: index("trials_cancer_types_idx").using(
      "gin",
      table.cancerTypes
    ),
    modalitiesIdx: index("trials_modalities_idx").using(
      "gin",
      table.modalities
    ),
    countriesIdx: index("trials_countries_idx").using("gin", table.countries),
    sourceIdx: index("trials_source_idx").on(table.source),
    sourceLastUpdatedIdx: index("trials_source_last_updated_idx").on(
      table.sourceLastUpdated
    ),
    crossRefIdx: index("trials_cross_ref_idx").using(
      "gin",
      table.crossReferenceIds
    ),
  })
);

// Track each ingestion run for monitoring and incremental updates
export const ingestionRuns = pgTable("ingestion_runs", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  source: sourceEnum("source").notNull(),
  startedAt: timestamp("started_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  status: text("status").notNull().default("running"), // "running" | "succeeded" | "failed"
  trialsSeen: integer("trials_seen").default(0),
  trialsInserted: integer("trials_inserted").default(0),
  trialsUpdated: integer("trials_updated").default(0),
  errorMessage: text("error_message"),
  metadata: jsonb("metadata"),
});

export type Trial = typeof trials.$inferSelect;
export type NewTrial = typeof trials.$inferInsert;
export type IngestionRun = typeof ingestionRuns.$inferSelect;
